# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170320_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_animal',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobby',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
